tmobile/DevEdge-IoTDevKit-ZephyrRTOS

west.yml
This fixes the URL for the CXD5605 module
=> modules: Fix CXD5605 URL

west.yml
Changed WiSeConnect URL to HTTPS to fix pipeline failure.
=> modules: Fix WiSeConnect URL

CODEOWNERS
Removed Jay from the CODEOWNERS file.
=> CODEOWNERS: Remove Jay Rickard from CODEOWNERS

drivers/modem/murata-1sc.c, dts/bindings/modem/murata,1sc.yaml
Removed the deprecated label binding as a requirement in the Murata 1SC bindings.
=> dts: bindings: Fix murata 1SC bindings

drivers/bluetooth/custom/rs9116w/rs9116w_ble_conn.c, drivers/bluetooth/custom/rs9116w/rs9116w_ble_gap.c, drivers/wifi/rs9116w/rs9116w.h, drivers/wifi/rs9116w/rs9116w_mgmt.c
Fixed RS9116 drivers not compiling in up-to-date zephyr.
=> drivers: Fix RS9116 driver compile on HEAD

drivers/modem/murata-1sc.c, include/zephyr/drivers/modem/murata-1sc.h
This is the Zephyr half corresponding to https://github.com/tmobile/DevEdge-IoTDevKit-ZephyrSDK/pull/37
This PR also moves some definitions from the drivers C file into a header so callers don't need to redefine certain values.
=> murata-1sc.c: Convert void* from int va_args call

drivers/sensor/cxd5605/cxd5605.c
Remove the force suspend power management option from the pm actions.
=> drivers: sensor: Remove force suspend from CXD5605

drivers/wifi/rs9116w/rs9116w_socket_offload.c
Fixed errno value/return value for a zero-sized recieve.
=> drivers: wifi: Fixed RS9116 response on zero sized recieves

drivers/wifi/rs9116w/rs9116w_socket_offload.c
Fixed the returned errno value for unboud udp sockets for RS9116W driver
=> drivers: wifi: Fix errno on udp recv unbound

drivers/wifi/rs9116w/rs9116w_socket_offload.c
Added fix so that the driver will adhere to the defined socket limits.
=> drivers: wifi: Fix RS9116 ignoring socket limit

drivers/wifi/rs9116w/Kconfig.rs9116w
Updated kconfig to properly set wiseconnect ICMP to true if ping is requested.
=> drivers: wifi: Fix ping in 9116 driver

boards/arm/tmo_dev_edge/tmo_dev_edge.dts, drivers/sensor/cxd5605/cxd5605.c, dts/bindings/sensor/sony,cxd5605.yaml
Removed dependency on label, and added all pins to DTS entry.
=> drivers: sensor: Fix cxd5605 dependence on GPIO_F label

drivers/wifi/rs9116w/rs9116w_mgmt.c
Driver now properly checks if init succeeds before trying to read from the 9116 chip.
=> drivers: wifi: Fix hang on failed device init

drivers/modem/murata-1sc.c
Fixed issue that prevented the murata modem driver from building if TLS was disabled.
=> drivers: modem: Fix Murata modem build without TLS

drivers/bluetooth/custom/rs9116w/rs9116w_ble_core.h
Fixed issues where older versions of "bt_addr_le_str" and "bt_hex" are no longer available.
=> drivers: bluetooth: Fix bt_keys log issues

boards/arm/tmo_dev_edge/tmo_dev_edge.dts
Added value for ODR for LPS22HH on devedge to allow sensor shell to function properly.
=> boards: arm: Add ODR to LPS22HH on DevEdge

CODEOWNERS, samples/subsys/shell/fs/boards/tmo_dev_edge.conf
Add configuration for the T-Mobile DevEdge in the fs shell sample.
=> samples: add tmo_dev_edge config in fs shell sample

CODEOWNERS, drivers/bluetooth/custom/rs9116w/Kconfig.rs9116w, samples/bluetooth/peripheral_hr/boards/tmo_dev_edge.conf, samples/bluetooth/peripheral_ht/boards/tmo_dev_edge.conf
Enabled the usage of the pre-made services with the RS9116W bluetooth driver.
=> drivers: bluetooth: Enable services on 9116 driver

drivers/modem/murata-1sc.c
Fixed issues where unset eDRX values would report as the same as from previous read.
=> drivers: modem: Fix incorrect reported edrx values

boards/arm/tmo_dev_edge/board.h
Added defines for HWID and BATMON ADCs in DevEdge board.h
=> boards: arm: Added defines for DevEdge ADCs

subsys/shell/modules/date_service.c
This fixes an issue with the 'date counter' command
=> subsys: shell: Fix 'date counter' command

drivers/sensor/cxd5605/cxd5605.c
Fix 1PPS signal check to use devicetree instead of a hard-coded board check.
=> drivers: sensor: Fix 1PPS check on CXD5605 driver

drivers/modem/murata-1sc.c
Fixed issue where multi segment SMS messages in
the UCS character set are improperly decoded.
=> drivers: modem: Fix UCS2 decode on 1SC

drivers/sensor/lis2dw12/lis2dw12.c, drivers/sensor/lis2dw12/lis2dw12.h
Added temperature conversion to celcius from a delta count value.
Signed-off-by: Kevin King <kevin.king101@t-mobile.com>
=> sensor: fixed ambient temperature in the lis2dw12 sensor driver.

drivers/sensor/cxd5605/cxd5605.c
This sets the reset gpio in the CXD5606 driver to change in sync with the power gpio, which keeps TCXO off during sleep.
=> drivers: sensor: Fix CXD5605 for low power

drivers/modem/murata-1sc.c, include/zephyr/drivers/modem/murata-1sc.h
Removed unused timers from PSM parameters.
=> drivers: modem: Improve PSM set on 1SC modem.

drivers/modem/murata-1sc.c
This increases the buffer size for dns lookups from 64 to 128
=> driver: modem: Increase size of dns buffer for 1SC

west.yml
Updated wiseconnect module for version with fix for 'spi_is_ready' warning.
=> modules: Fix warning in wiseconnect module

boards/arm/efm32pg_stk3402a/Kconfig.defconfig, boards/arm/tmo_dev_edge/Kconfig.defconfig, drivers/counter/counter_gecko_rtcc.c, drivers/counter/gecko_rtcc.c, subsys/shell/modules/date_service.c
Switch TIME_GECKO_RTCC back to COUNTER_GECKO_RTCC
They should be interchangeable now
Add persistence to SiLab's counter_gecko_rtcc.c
Remove most of ds3231 references from my gecko_rtcc.c file Fix date_service mistake with TIMER vs TIMER_COUNTER Add sections for CONFIG_COUNTER_GECKO_RTCC differences
Signed-off-by: Dennis Ruffer <Dennis.Ruffer1@T-Mobile.com>
=> drivers: counter: Remove ds3231 from Gecko RTCC and add persistence

.gitattributes, subsys/shell/modules/date_service.c
Fix date_service mistake with TIMER vs TIMER_COUNTER. Add sections for CONFIG_COUNTER_GECKO_RTCC differences. Add this file to .gitattributes so we consider this as ours.
Signed-off-by: Dennis Ruffer <Dennis.Ruffer1@T-Mobile.com>
=> drivers: counter: Re-add date_service persistence and .gitattributes

drivers/sensor/cxd5605/cxd5605.c
Fixed issue where an assert would be raised if the off command was called in the cxd5605 driver.
=> driver: sensor: Fix assert error in cxd driver

drivers/bluetooth/custom/rs9116w/Kconfig.rs9116w, drivers/bluetooth/custom/rs9116w/rs9116w_ble_core.c
Fixed 9116 driver to better handle names longer than 16bytes.
=> driver: bluetooth: Handle long configured names

drivers/wifi/rs9116w/rs9116w_mgmt.c
Fixed 9116 handling of unknown security types/wpa3 security.
=> drivers: wifi: Fix handling of security types

drivers/modem/murata-1sc.c
Increased SMS send timeout to eliminate spurious timeout errors.
=> drivers: modem: Fix SMS send timeout

drivers/sensor/lis2dw12/lis2dw12.c
This fixes a small issue where a variable needs to be declared const
=> drivers: sensor: Fix LIS2DW12 const issue

boards/arm/tmo_dev_edge/board.c
This adds battery charge/discharge tables to the DevEdge board file
=> boards: arm: Add battery charge/discharge tables on DevEdge

drivers/sensor/tsl2540/tsl2540.c, drivers/sensor/tsl2540/tsl2540.h, drivers/sensor/tsl2540/tsl2540_trigger.c, include/zephyr/drivers/sensor/tsl2540.h
This is the first pass to prepare the driver to support the TSL2540's threshold alert capability.
=> Add threshold interrupt support to TSL2540 driver

drivers/modem/modem_shell.c
Added a warning to modem shell for SMS messages larger than the specified maximum value.
=> modem: Add warning to modem shell for long SMS

subsys/net/ip/Kconfig.ipv6
In case native IPv6 is disabled, Kconfig entries related to native IPv6 stack should not be enabled. Otherwise, circular dependencies can be created if native stack is disabled, as in case of recent changes in NET_IPV6_RA_RDNSS option (where a dependency for a native stack module was enabled).
=> net: ipv6: Fix Kconfig dependencies when native IPv6 is disabled

drivers/sensor/tmp108/tmp108.c
Fixed tmp108 build when device_pm is not enabled
=> driver: sensor: fix tmp108 build

drivers/modem/modem_sms.h
Fixed modem sms header to include necessary headers.
=> drivers: modem: fix includes for modem sms

drivers/sensor/sx9328/sx9328.c, drivers/sensor/sx9328/sx9328_trigger.c
Fixed issues preventing the SX9328 driver from building when logging is enabled.
=> drivers: sensor: Fix logging build of SX9328

boards/arm/tmo_dev_edge/board.c
This fixes a build warning associated with an unused parameter
=> boards: arm: Fix build warning with unused param

drivers/modem/murata-1sc.c
Fix issue of using wrong allocation check in the 1SC socket close function.
=> drivers: modem: Fix 1SC socket close

boards/arm/tmo_dev_edge/tmo_dev_edge.dts
Enable using the DPD mode on our SPI NOR chip.
=> boards: arm: Enable DPD flag on flash chip

drivers/wifi/rs9116w/rs9116w_mgmt.c, west.yml
Enabled background scan/scan whilst connected in the RS9116 WiFi driver.
=> drivers: wifi: Enable background scan

boards/arm/tmo_dev_edge/tmo_dev_edge.dts
fix building test samples by moving watchdog nodes from chosen to alias
=> boards: tmo_dev_edge: dts chosen watchdog to alias

.github/workflows/tmo-nightly-merge-main-tmo-main.yml
Reather than reverting, this will preserve the record of when this was turned off and on.
=> github: workflows: Turn nightly merge back on

.gitattributes
unable to reproduce issue with long commands in history scrolling
.gitattributes: remove shell_ops.c
=> subsys: shell: shell_ops.c  take from upstream
