boards/arm/tmo_dev_edge/tmo_dev_edge.dts

Removed label properties and cleaned up formating in the tmo_dev_edge board dts file.

boards: arm: Cleanup tmo_dev_edge dts file

---

west.yml

Updated WiSeConnect module for compatibility with newer Zephyr.

modules: Updated WiSeConnect module

---

west.yml

Updated CXD5605 lib module to use the extended config struct

modules: update CXD5605 lib

---

drivers/sensor/tmp108/tmp108.c
include/zephyr/drivers/sensor.h

Added sensor attribute for adding a user callback to the driver.

Updated for as6212 sample. added application user callback attribute.

---

drivers/modem/murata-1sc.c

Added check for AT persistence in the Murata 1SC modem driver.

drivers: modem: Enabled AT Persistence on 1SC

---

subsys/shell/shell_ops.c

This fixes scrolling long commands in command history in the shell

shell: Fix scrolling long commands in history

---

CODEOWNERS
boards/arm/tmo_dev_edge/tmo_dev_edge.dts
drivers/sensor/lis2dw12/lis2dw12.c
drivers/sensor/lis2dw12/lis2dw12.h
include/zephyr/drivers/sensor.h
include/zephyr/drivers/sensor/lis2dw12.h

Signed-off-by: Kevin King <kevin.king101@t-mobile.com>

Updated the LIS2DW12 driver for motion based interrupts.

---

CODEOWNERS
boards/arm/tmo_dev_edge/tmo_dev_edge.dts
drivers/sensor/lis2dw12/lis2dw12.c
drivers/sensor/lis2dw12/lis2dw12.h
drivers/sensor/lis2dw12/lis2dw12_trigger.c
include/zephyr/drivers/sensor/lis2dw12.h

Signed-off-by: Kevin King <kevin.king101@t-mobile.com>

lis2dw12 demo driver side changes from the last PR.

---

drivers/modem/murata-1sc.c

1SC Sendto no longer sets up a connection, preventing erroneous EISCONN error.

driver: modem: Fix murata 1sc sendto

---

soc/arm/silabs_exx32/common/soc_power.c

Fixed EM2/EM3 functionality to not hang on idle after wake.

soc: arm: Fix Gecko EM2/EM3 functionality

---

.gitattributes
subsys/net/lib/http/http_client.c

This changes an instance of POLLIN to ZSOCK_POLLIN

net: http_client: Change POLLIN to ZSOCK_POLLIN

---

samples/bluetooth/peripheral_hids/README.rst
samples/boards/nxp_s32/netc/README.rst

Fixed sample documentation to allow pipleine to pass

samples: Fix documentation

---

drivers/modem/murata-1sc.c

Added interrupt handler for modem wakes host interrupt.

driver: modem: Add wake interrupt to 1SC driver

---

drivers/sensor/tmp108/tmp108.c

Added device power management functionality to the tmp108 as6212 combo driver.

drivers: sensor: Add PM to tmp108/as6212 driver

---

drivers/sensor/lis2dw12/lis2dw12.c

Added device PM functionality to the lis2dw12 accelerometer driver

drivers: sensor: Add PM to lis2dw12

---

drivers/bluetooth/custom/rs9116w/rs9116w_ble_gatt.c

Fixed issue where CCCs weren't properly being cleared on disconnect.

driver: bluetooth: Fixed -17 CCC error

---

boards/arm/efm32pg_stk3402a/efm32pg_stk3402a-pinctrl.dtsi

Somehow, the settings got changed after I tested them.

board: arm: efm32pg_stk3402a Fix pinctrl usart0_default settings

---

drivers/modem/Kconfig.murata-1sc
drivers/modem/murata-1sc.c

Added configuration option for SNI size on the 1SC modem.

drivers: modem: Increased maximum size for SNI

---

drivers/modem/murata-1sc.c
drivers/wifi/rs9116w/rs9116w_mgmt.c
include/zephyr/net/wifi_mgmt.h
subsys/net/l2/wifi/wifi_mgmt.c

Fix wifi management and ifaces to be up to date with upstream.

net: Fix interfaces to work with new offload

---

.gitattributes
subsys/shell/shell_cmds.c

Added the shell comment command

shell: Add shell command command rem

---

drivers/modem/Kconfig
drivers/modem/modem_shell.c
drivers/modem/modem_socket.c
drivers/modem/modem_socket.h
drivers/modem/murata-1sc.c
drivers/modem/murata-1sc.h
drivers/sensor/cxd5605/cxd5605.c
include/zephyr/drivers/modem/murata-1sc.h

Add changes to fix 1SC driver build with up-to-date changes from upstream zephyr

drivers: modem: catch 1sc driver up

---

west.yml

Updated modules to match upstream, and updated wiseconnect to fix SYS_INIT bug.

modules: updated modules

---

include/zephyr/net/http/client.h
subsys/net/lib/http/http_client.c

Added timeout for individual packets to the HTTP client code.

net: http: Added packet timeout to http client

---

drivers/adc/Kconfig
drivers/adc/Kconfig.gecko

Fix mistake in merging IADC fix.

drivers: adc: Fix merge mistake

---

drivers/modem/murata-1sc.c

Fixed issue where a stack overflow would occur in 1SC driver init with standard stack size.

drivers: modem: Fix stack overflow

---

drivers/power_domain/power_domain_gpio.c
drivers/power_domain/power_domain_regulator.c

Clarified the messages emmited on domain suspend/resume.

drivers: power domain: Clarified messages

---

drivers/fuel_gauge/charger_act81461.c
drivers/regulator/regulator_act81461.c
drivers/regulator/regulator_act81461.h
include/zephyr/drivers/fuel_gauge/act81461.h
include/zephyr/drivers/regulator/act81461.h

Improved interrupt handling logic for the ACT81461 PMIC driver.

drivers: regulator: Fix PMIC interrupts

---

drivers/bluetooth/custom/rs9116w/rs9116w_ble_core.c
include/zephyr/drivers/bluetooth/rs9116w.h

Added ability to read MAC address to RS9116 BLE driver.

drivers: bluetooth: Add MAC read to 9116 driver
